(ns cdq.graphics)

(defprotocol Graphics
  (delta-time [_])
  (frames-per-second [_])
  (clear-screen! [_])
  (handle-draws! [_ draws])
  (draw-on-world-viewport! [_ f])
  (set-camera-position! [_ position])
  (world-viewport-width [_])
  (world-viewport-height [_])
  (camera-position [_])
  (inc-zoom! [_ amount])
  (camera-frustum [_])
  (visible-tiles [_])
  (camera-zoom [_])
  (draw-tiled-map! [_ tiled-map color-setter])
  (set-cursor! [_ cursor])
  (pixels->world-units [_ pixels])
  (sprite [_ texture-path])
  (sub-sprite [_ sprite [x y w h]])
  (sprite-sheet [_ texture-path tilew tileh])
  (sprite-sheet->sprite [_ sprite [x y]]))

(defprotocol MouseViewports
  (world-mouse-position [_])
  (ui-mouse-position [_]))
