(ns cdq.input)

(defprotocol Input
  (player-movement-vector [_])
  (zoom-in? [_])
  (zoom-out? [_])
  (close-windows? [_])
  (toggle-inventory? [_])
  (toggle-entity-info? [_])
  (unpause? [_])
  (open-debug-button-pressed? [_])
  (mouse-position [_])
  (left-mouse-button-just-pressed? [_])
  (enter-just-pressed? [_])
  (controls-info-text [_]))
