(ns cdq.stage)

(defprotocol Stage
  (add-actor! [_ actor])
  (draw! [_])
  (act! [_])
  (mouse-on-actor? [_])
  (root [_])
  (set-item! [stage cell item])
  (remove-item! [stage cell])
  (selected-skill [stage])
  (add-skill! [stage skill])
  (remove-skill! [stage skill])
  (show-message! [stage text])
  (show-modal! [stage opts])
  (inventory-visible? [stage])
  (inventory-cell-with-item? [_ actor])
  (window-title-bar? [_ actor])
  (button? [_ actor]))
