(ns cdq.stage)

(defprotocol Stage
  (viewport-width [stage])
  (viewport-height [stage])
  (inventory-window-visible? [stage])
  (toggle-inventory-visible! [stage])
  (show-modal-window! [stage ui-viewport {:keys [title text button-text on-click]}])
  (set-item! [stage cell item-properties])
  (remove-item! [stage inventory-cell])
  (add-skill! [stage skill-properties])
  (remove-skill! [stage skill-id])
  (show-text-message! [stage message])
  (toggle-entity-info-window! [_])
  (close-all-windows! [_])
  (action-bar-selected-skill [_])
  (actor-information [_ actor])
  (mouseover-actor [_ mouse-position]))
