{:gdx-app [[gdl.db (properties-file db undefined-data-ks)]
           [gdl.schema (schemas)]
           [gdl.assets (manager)]
           [gdl.graphics.batch (batch)]
           [gdl.graphics.shape-drawer (sd-texture sd)]
           [gdl.graphics.text (default-font)]
           [gdl.screen (screens screen-k)]
           [gdl.graphics.cursors (cursors)]
           [gdl.graphics.gui-view (view)]
           [gdl.graphics.world-view (view)]]
 :world [[moon.world.tiled-map (tiled-map)]
         [moon.world.mouseover (eid)]
         [moon.player (eid)]
         [moon.world.grid (grid)]
         [moon.world.time (elapsed delta)]
         [moon.world.entities (content-grid ids->eids)]
         [moon.screens.world (paused? tick-error)]
         [moon.world.potential-fields (pf-cache)]
         [moon.world.raycaster (raycaster)]
         [moon.widgets.player-message (message-to-player)]]}
