(ns gdl.graphics)

(defprotocol Graphics
  (delta-time [_])
  (frames-per-second [_])
  (clear-screen! [_])
  (handle-draws! [_ draws])
  (draw-on-world-viewport! [_ f])
  (sprite [_ texture])
  (sub-sprite [_ sprite [x y w h]])
  (sprite-sheet [_ texture-path tilew tileh])
  (sprite-sheet->sprite [_ sprite-sheet [x y]])
  (set-camera-position! [_ position])
  (world-viewport-width [_])
  (world-viewport-height [_])
  (camera-position [_])
  (inc-zoom! [_ amount])
  (camera-frustum [_])
  (visible-tiles [_])
  (camera-zoom [_]))
