(ns cdq.create.txs
  (:require [cdq.multifn]))

(defn do! [ctx]
  (cdq.multifn/add-methods! '[{:required [cdq.ctx/do!]}
                              [[cdq.tx.assoc
                                :tx/assoc]
                               [cdq.tx.assoc-in
                                :tx/assoc-in]
                               [cdq.tx.dissoc
                                :tx/dissoc]
                               [cdq.tx.effect
                                :tx/effect]
                               [cdq.tx.mark-destroyed
                                :tx/mark-destroyed]
                               [cdq.tx.mod-add
                                :tx/mod-add]
                               [cdq.tx.mod-remove
                                :tx/mod-remove]
                               [cdq.tx.pay-mana-cost
                                :tx/pay-mana-cost]
                               [cdq.tx.pickup-item
                                :tx/pickup-item]
                               [cdq.tx.set-cooldown
                                :tx/set-cooldown]
                               [cdq.tx.add-text-effect
                                :tx/add-text-effect]
                               [cdq.tx.add-skill
                                :tx/add-skill]
                               [cdq.tx.set-item
                                :tx/set-item]
                               [cdq.tx.remove-item
                                :tx/remove-item]
                               [cdq.tx.event
                                :tx/event]
                               [cdq.tx.toggle-inventory-visible
                                :tx/toggle-inventory-visible]
                               [cdq.tx.show-message
                                :tx/show-message]
                               [cdq.tx.show-modal
                                :tx/show-modal]
                               [cdq.tx.sound
                                :tx/sound]
                               [cdq.tx.state-exit
                                :tx/state-exit]
                               [cdq.tx.state-enter
                                :tx/state-enter]
                               [cdq.tx.audiovisual
                                :tx/audiovisual]
                               [cdq.tx.spawn-alert
                                :tx/spawn-alert]
                               [cdq.tx.spawn-line
                                :tx/spawn-line]
                               [cdq.tx.deal-damage
                                :tx/deal-damage]
                               [cdq.tx.move-entity
                                :tx/move-entity]
                               [cdq.tx.spawn-projectile
                                :tx/spawn-projectile]
                               [cdq.tx.spawn-effect
                                :tx/spawn-effect]
                               [cdq.tx.spawn-item
                                :tx/spawn-item]
                               [cdq.tx.spawn-creature
                                :tx/spawn-creature]
                               [cdq.tx.spawn-entity
                                :tx/spawn-entity]]]))
