([forge.mapgen.uf-caves (uf-grounds uf-walls sprite-size scaling)]
 [forge.screens.editor
  (component-row-cols overview property-k-sort-order)]
 [forge.mapgen.modules
  (floor-modules-row-height
   height
   transition-modules-row-width
   floor-modules-row-width
   scale
   file
   width
   number-modules-y
   number-modules-x
   transition-modules-row-height
   transition-modules-offset-x
   floor-idxvalue
   module-offset-tiles)]
 [forge.mapgen.generate (spawn-creatures?)]
 [forge.core
  (effect-body-props
   db-properties
   offsets
   z-orders
   info-text-k-order
   black
   max-delta-time
   world-viewport-height
   shape-drawer
   world-tiled-map
   spawn-enemies?
   los-checks?
   world-delta
   default-font
   world-viewport-width
   cursors
   world-unit-scale
   white
   minimum-body-size
   paused?
   gui-viewport
   explored-tile-corners
   *unit-scale*
   content-grid
   max-speed
   world-viewport
   gui-viewport-height
   db-schemas
   render-z-order
   app-screens
   dev-mode?
   message-to-player
   current-screen-key
   ray-caster
   batch
   shape-drawer-texture
   player-eid
   *on-clicked-actor*
   ids->eids
   speed-schema
   player-message-duration-seconds
   tick-error
   asset-manager
   show-body-bounds
   mouseover-eid
   info-color
   undefined-data-ks
   db-properties-file
   world-grid
   val-max-schema
   *info-text-entity*
   gui-viewport-width
   elapsed-time)]
 [forge.dev.loop (obj refresh-error thrown nrepl-server app-ns-sym)]
 [forge.world.potential-fields
  (diagonal-check-indizes pf-cache factions-iterations)]
 [forge.ui.inventory
  (empty-inventory
   droppable-color
   not-allowed-color
   cell-size
   slot->y-sprite-idx)]
 [forge.mapgen
  (idxvalues get-adj-num current-order turn-ratio diagonal-steps)]
 [forge.entity
  (neutral-color
   hpbar-colors
   borders-px
   outline-alpha
   friendly-color
   enemy-color
   shout-radius)]
 [forge.controls (zoom-speed window-hotkeys help-text)]
 [forge.screens.map-editor (world-id camera-movement-speed infotext)]
 [forge.screens.world
  (tile-grid?
   cell-occupied?
   see-all-tiles?
   disallowed-keys
   highlight-blocked-cell?
   pausing?
   explored-tile-color
   cell-entities?
   potential-field-colors?)])
